project:
  type: book
  output-dir: pdf

book:
  title: "Network Centrality in College Football"
  subtitle: "Applying Graph Theory to Sports Competition Analysis"
  chapters:
    - index.qmd

bibliography: references.bib
link-citations: true
citeproc: true

format:
  pdf:
    toc: false
    number-sections: true
    top-level-division: section
    colorlinks: true
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    fontsize: 12pt
    documentclass: article
    fig-pos: "H"
    code-block-bg: true
    code-block-border-left: "#ba68c8"
    linestretch: 1.2
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \usepackage{fancyhdr}
        \usepackage{lastpage}
        \pagestyle{fancy}
        \fancyhead[L]{\footnotesize Network Centrality in College Football}
        \fancyhead[R]{\footnotesize \thepage\ of \pageref{LastPage}}
        \fancyfoot[C]{}
        \usepackage{authblk}
        \usepackage{microtype}
        \usepackage{booktabs}
        \usepackage{tabularx}
        \usepackage[table]{xcolor}
        \definecolor{lightgray}{gray}{0.9}
        \usepackage{graphicx}
        \usepackage{caption}
        \usepackage{float}
        \raggedbottom
        \renewcommand\Authfont{\fontsize{12}{14.4}\selectfont}
        \renewcommand\Affilfont{\fontsize{10}{12}\selectfont\itshape}
        \setlength{\affilsep}{1em}
        \author{Yevheniy Chuba}
        \date{November 2025 -- Version 1.0}
        \renewcommand{\maketitle}{%
          \begin{center}
            {\LARGE\bfseries Network Centrality in College Football}\\[0.4em]
            {\large Applying Graph Theory to Sports Competition Analysis}\\[1.5em]
            {\Authfont Yevheniy Chuba}\\[0.5em]
            {\Affilfont University of Pittsburgh -- MDS}\\[1.5em]
            {\normalsize \textit{Version 1.0 -- November 2025}}\\[0.5em]
            {\footnotesize \textit{Author note: This research applies network science methods to analyze competitive relationships in college football, demonstrating graph theory concepts through sports data.}}\\[0.5em]
            {\footnotesize \textit{Status: Network Science Research Publication}}\\[0.2em]
          \end{center}
        }

execute:
  echo: false
  warning: false
  message: false
  cache: false
  dpi: 300

jupyter: python3


